/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoQueryRouteImport } from './routes/demo/query'
import { Route as DemoOrpcRouteImport } from './routes/demo/orpc'
import { Route as DemoFormRouteImport } from './routes/demo/form'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoAuthRouteImport } from './routes/demo/auth'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/storybook',
  path: '/storybook',
  getParentRoute: () => DemoRoute,
} as any)
const DemoQueryRoute = DemoQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => DemoRoute,
} as any)
const DemoOrpcRoute = DemoOrpcRouteImport.update({
  id: '/orpc',
  path: '/orpc',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/drizzle',
  path: '/drizzle',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAuthRoute = DemoAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DemoRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/auth': typeof DemoAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/orpc': typeof DemoOrpcRoute
  '/demo/query': typeof DemoQueryRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/auth': typeof DemoAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/orpc': typeof DemoOrpcRoute
  '/demo/query': typeof DemoQueryRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/auth': typeof DemoAuthRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/orpc': typeof DemoOrpcRoute
  '/demo/query': typeof DemoQueryRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo'
    | '/demo/auth'
    | '/demo/drizzle'
    | '/demo/form'
    | '/demo/orpc'
    | '/demo/query'
    | '/demo/storybook'
    | '/demo/table'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/demo/auth'
    | '/demo/drizzle'
    | '/demo/form'
    | '/demo/orpc'
    | '/demo/query'
    | '/demo/storybook'
    | '/demo/table'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo'
    | '/demo/auth'
    | '/demo/drizzle'
    | '/demo/form'
    | '/demo/orpc'
    | '/demo/query'
    | '/demo/storybook'
    | '/demo/table'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoRoute: typeof DemoRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/query': {
      id: '/demo/query'
      path: '/query'
      fullPath: '/demo/query'
      preLoaderRoute: typeof DemoQueryRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/orpc': {
      id: '/demo/orpc'
      path: '/orpc'
      fullPath: '/demo/orpc'
      preLoaderRoute: typeof DemoOrpcRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/auth': {
      id: '/demo/auth'
      path: '/auth'
      fullPath: '/demo/auth'
      preLoaderRoute: typeof DemoAuthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemoRouteChildren {
  DemoAuthRoute: typeof DemoAuthRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoOrpcRoute: typeof DemoOrpcRoute
  DemoQueryRoute: typeof DemoQueryRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAuthRoute: DemoAuthRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoFormRoute: DemoFormRoute,
  DemoOrpcRoute: DemoOrpcRoute,
  DemoQueryRoute: DemoQueryRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoRoute: DemoRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
