/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoQueryRouteImport } from './routes/demo/query'
import { Route as DemoFormRouteImport } from './routes/demo/form'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => DemoRoute,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/storybook',
  path: '/storybook',
  getParentRoute: () => DemoRoute,
} as any)
const DemoQueryRoute = DemoQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/form': typeof DemoFormRoute
  '/demo/query': typeof DemoQueryRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/form': typeof DemoFormRoute
  '/demo/query': typeof DemoQueryRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/form': typeof DemoFormRoute
  '/demo/query': typeof DemoQueryRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo'
    | '/demo/form'
    | '/demo/query'
    | '/demo/storybook'
    | '/demo/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/demo/form'
    | '/demo/query'
    | '/demo/storybook'
    | '/demo/table'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo'
    | '/demo/form'
    | '/demo/query'
    | '/demo/storybook'
    | '/demo/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoRoute: typeof DemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/query': {
      id: '/demo/query'
      path: '/query'
      fullPath: '/demo/query'
      preLoaderRoute: typeof DemoQueryRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoFormRoute: typeof DemoFormRoute
  DemoQueryRoute: typeof DemoQueryRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoFormRoute: DemoFormRoute,
  DemoQueryRoute: DemoQueryRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoRoute: DemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
